# Generated by Django 5.2.11 on 2026-02-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeupload',
            name='parsed_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
